baseURL = "https://prs2rnn.github.io/"
theme = "nostyleplease"
title = "My Blog"
languageCode = "en-US"
publishDir = "docs"

enableGitInfo = true
[frontmatter]
    lastmod = [":git", "lastmod", "date", "publishDate"]

[minify]
    disableHTML = false
    disableCSS = false
    disableJS = false

[sitemap]
    changefreq = 'monthly'
    priority = 0.5
    filename = 'sitemap.xml'

[permalinks]
  posts = "/posts/:slug/"


[params]
    favicon = "images/favicon.png"
    images = ["images/share.png"]
